# Generated by Django 4.1.7 on 2023-02-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='pattern',
            new_name='pattern_pdf',
        ),
    ]
