# Generated by Django 4.1.7 on 2023-02-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patterns', '0002_rename_pattern_pattern_pattern_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
