# Generated by Django 4.1.7 on 2023-02-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patterns', '0004_pattern_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pattern',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_patterns', to=settings.AUTH_USER_MODEL),
        ),
    ]
