# Generated by Django 4.1.7 on 2023-02-19 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patterns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('is_favorite', models.BooleanField()),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patterns.pattern')),
            ],
        ),
    ]
