# Generated by Django 4.1.7 on 2023-02-20 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patterns', '0005_remove_pattern_user_id_pattern_user'),
        ('Photos', '0004_alter_photo_pattern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pattern_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patterns.pattern'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(upload_to='photos/images', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
