# Generated by Django 4.1.7 on 2023-02-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0005_alter_photo_pattern_id_alter_photo_photo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pattern_id',
            new_name='pattern',
        ),
    ]
